#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
# Add other sub domains
# A bash script that display information about the subdomains 
