#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
# Add other sub domains
# A bash script that display information about the subdomains

display_info() {
	local domain="$1"
	local subdomain="$2"

	# Check if the subdomain is provided
	if [ -n "$subdomain" ]; then
		query_result=$(dig "$subdomain.$domain" +short)
		record_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk 'FNR==2 {print $4}')
		# record_type=$(dig +short "$subdomain.$domain" | awk 'NR==1{print $1}')
	
		echo "The subdomain $subdomain is a $record_type record and points to $query_result"
	else
		subdomains=("www" "lb-01" "web-01" "web-02")
		for sub in "${subdomains[@]}"; do
			query_result=$(dig "$sub.$domain" +short)
			record_type=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'FNR==2 {print $4}')
			# record_type=$(dig "$sub.$domain" +short -t ANY | awk '{print $NF}')
			echo "The subdomain $sub is a $record_type record and points to $query_result"
		done
		return
	fi
}
# Assign parameters to variables
domain="$1"
subdomain="$2"

# Call the function to display information
display_info "$domain" "$subdomain"



