#!/usr/bin/env bash
# Update package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# start Nginx
sudo service nginx restart

# Create a default index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to use the custom index.html file
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF'

# Restart Nginx without using systemctl
sudo service nginx restart

