#!/usr/bin/env bash
# Installing and configuring haproxy load balancer using the roundrobin algorithm
sudo apt-get update

sudo apt-get install --no-install-recommends -y software-properties-common

sudo add-apt-repository -y ppa:vbernat/haproxy-2.8

sudo apt-get install -y haproxy=2.8.\*

sudo service haproxy start

multiline_text=$(cat <<EOF

frontend web_frontend
	bind *:80
	mode http
	default_backend web_servers

backend web_servers
	mode http
	balance roundrobin
	server web-01 34.229.55.3:80 check
	server web-02 100.26.152.7:80 check
EOF
)

echo "$multiline_text" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart

