#!/usr/bin/env bash
# creating backup for database

# Check if the correct number of arguments is provided
if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <mysql_root_password>"
	exit 1
fi


# MySQL dump command
mysqldump -u root -p"$1" --all-databases > backup.sql

# Create a compressed tar archive
tar -czf "$(date +%d-%m-%Y)".tar.gz backup.sql
i
