#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
# Must show all proesses for all users including those which might not have a TTY
# display in a user oriented format
# show process hierachy

ps aux